### ISSUE TITLE
Incorrect counts

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#138]
"Segmentations" checkbox shows incorrect case count, and is not consistent with itself - the number of cases in the right is different from the counts on the left.

![image](https://user-images.githubusercontent.com/313942/86016832-4c80fc80-b9f1-11ea-980a-37e2a6969609.png)

**Comment by G-White-ISB** [comment]
Our derived data numbers are way off. I'm checking that today.

**Comment by s-paquette** [comment]
Note, I haven't migrated over the new table/Solr core setup, so I would ignore the counts entirely for now. Until I get that done we can't really rely on those.

**Comment by fedorov** [comment]
Also, I just noticed this - why is there a piechart for "SOP CLASS UID"?

**Comment by s-paquette** [comment]
@fedorov Can you have a look at the counts now? I've fixed what was causing them to be off.

**Comment by fedorov** [comment]
That specific error is gone, thank you!

> why is there a piechart for "SOP CLASS UID"?

I didn't realize you added that new tab corresponding to the name matching SOPClass UID. The name of that tab (and the piechart) should be "Object class", since we are showing names of the classes, not the UIDs that identify those classes.

There is also a new "incorrect count" error reported by @rkikinis, which I was able to reproduce. I am adding it here, since I do not know if it is the same or a new issue:

![image](https://user-images.githubusercontent.com/313942/86541884-a34d7100-bede-11ea-9825-d54d884fb665.png)

**Comment by s-paquette** [comment]
@fedorov Is this fixed on dev?

**Comment by madelyngreyes** [comment]
I still see the same functionality as Ron/Andrey's most recent input on the idc-dev tier.

![Screen Shot 2020-07-07 at 2 11 28 PM](https://user-images.githubusercontent.com/16824894/86824465-2c3de700-c05c-11ea-914f-d5fcc33e4245.png)

I have notifed Suzanne and is looking into this.

**Comment by G-White-ISB** [comment]
No it's a different issue only relevant to the quantitative measurement
filters. These filters  generate  an incorrect parameter argument in the
server call and so the requested URL is returning a 404. I think I can fix
this.
George

**Comment by s-paquette** [comment]
Ah, there's really two issues--one of which I fixed (the numbers are included records without derived data) and then I suspect the second one might be URL length. URLs have a max length, and selecting all the filters in that list might be going over, causing it to truncate.

**Comment by fedorov** [comment]
Confirmed this is fixed in dev.
