### ISSUE TITLE
Age at diagnosis none selection from Search Results panel broken

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#200]
On the IDC dev tier if an end-user selected the Filter option None from the Search Results panel, the filter option is displayed as NaN-NaN within the Filter Definition panel.  

Also, the Search result panel doesn't update to None only when the filter option None is selected. All possible filter options are still displayed. 

<img width="684" alt="Age at diagnosis none filter option" src="https://user-images.githubusercontent.com/16824894/90271456-d9f5a000-de29-11ea-9d97-f34f2b502919.PNG">

**Comment by madelyngreyes** [comment]
The same can be seen when you go the Derived tab, Quantitative Analysis, then select a None filter option.

**Comment by s-paquette** [comment]
@madelyngreyes Okay, should be working again.

**Comment by madelyngreyes** [comment]
On the exploration page, the selection of the Age at Diagnosis: None filter doesn't update the pie chart to display only the none filter option selected. 

Another point I noticed is the text in the Filter Definition panel displays the text, "NaN-NaN". I have taken a video and a screenshot of the functionality below. 

<img width="960" alt="IDC - age at diagnosis bug still present in the IDC dev tier" src="https://user-images.githubusercontent.com/16824894/92778362-1821a900-f36f-11ea-9bcb-b6ad77c72394.PNG">


video: https://screencast-o-matic.com/watch/cYQ6bAHWF9

Also, then when you then go to refresh the page the page reloads but, displays the error message, "Encountered an error when attempting to load the page - please contact the administrator."

<img width="960" alt="IDC - contact system admin error message after age at diagnosis none selection reload" src="https://user-images.githubusercontent.com/16824894/92777826-9467bc80-f36e-11ea-8076-0636d68a4f5c.PNG">

**Comment by G-White-ISB** [comment]
I removed the 'none' box for now. But there is still a backend issue. If I send both a range filter and a none selection filter, ie 
filters= {'age_at_diagnosis': 'None', 'collection_id': ['tcga_luad'], 'age_at_diagnosis_btw': [67, 89]}, then the 'None' attribute is missing from the age_at_diagnosis category. It seems you cannot apply the  'age_at_diagnosis' and 'age_at_diagnosis_btw' filters at the same time

**Comment by s-paquette** [comment]
Ah, I hadn't realized you were sending it twice.

So, you can't send the same attribute twice. If you do, one will overwrite the over. You need to send it once. Since we need to make sure the _btw is parsed, you send it as _btw. None just goes in as it's own value. So:

{ 'age_at_diagnosis_btw': [[x, y], 'None']} should work

**Comment by s-paquette** [comment]
Ah, discovered a bug which will make that fail, but it's a simple fix. I'll merge it in shortly.

**Comment by s-paquette** [comment]
@G-White-ISB 
So, note, there's still a front-end issue. If someone clicks on 'None' from the pie-chart, it's sending [None, None] as the values. What it should send is:

{ 'age_at_diagnosis': ['None']}

Then if they add a range:

{ 'age_at_diagnosis_btw': [[x, y], 'None']}
