### ISSUE TITLE
Unable to export BQ manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#703]
**General description**

Trying to export a cohort defined as SM filter, I get this error in test tier:

![image](https://user-images.githubusercontent.com/313942/129764793-a3c96b51-5abd-4f23-9159-61b9a98040e6.png)

and this in dev tier:

![image](https://user-images.githubusercontent.com/313942/129764827-ba47719b-7246-46b5-845e-3bc0fe93ba98.png)

**Steps to reproduce the behavior**

1. select "Slide microscopy" in Modality as a filter
2. export cohort to BQ

**Screenshots**

**Your System**
 - OS: macOS
 - Browser Chrome
 - Version 92.0.4515.131

**Other Comments**

**Comment by s-paquette** [comment]
There appear to be multiple sources of this error: 1) An issue with downloading manifests due to cursor code placed to support larger collections and deep paging, 2) a problem with the name change of the BQ UUID columns, 3) a problem with pulling the correct non-derived filters. Should be fixed now.

**Comment by fedorov** [comment]
> Should be fixed now.

Can you clarify which one should be fixed now and on which tier?

**Comment by s-paquette** [comment]
@pgundluru For testing on this one you'll want to use a series of cohorts:
- a cohort with ONE original filter
- a cohort with ONE derived filter
- a cohort with ONE each derived and original filters
- a cohort with TWO or more derived filters
- a cohort with TWO or more derived filters AND an original filter
- a cohort with ONE related filter (this must include a filter for a TCGA collection, as only TCGA collections can have related filters)
- a cohort with ONE each of original and related (this must include a filter for a TCGA collection, as only TCGA collections can have related filters)

Note that you should avoid BMI = None as a related data filter as there's a known bug in exports with that value. 

There are no TCGA collections with derived data so a combination of a related filter (which requires a TCGA collection filter) and a derived filter is not valid, which is why you won't see that in this list.

**Comment by s-paquette** [comment]
> > Should be fixed now.
> 
> Can you clarify which one should be fixed now and on which tier?

Build is still pending, I'll flag the ticket as testing needed once it's complete.

**Comment by fedorov** [comment]
@pgundluru is this still an issue?

**Comment by s-paquette** [comment]
This is still an issue with TCGA related filters, and I'm working on a fix for that at the moment.

**Comment by s-paquette** [comment]
@pgundluru I can't seem to replicate the TCGA issue now. Can you let me know what your filters were when you got this error?

**Comment by pgundluru** [comment]
I was able to reproduce the issues with TCGA cohorts by doing the below 2 tests 

Test 1 

1. Go to https://portal.imaging.datacommons.cancer.gov/explore/ 
2.  Select search scope - collections - TCGA
3.  Select one original filter - Body part examined - Abdomen and one related filter - Disease code - BLCA
4. Click on save cohort and then when i go to cohort page and select the cohort and click on export manifest - BQ 
Result - gives following error message with nothing else in dev console "Cohort ID 246: Unable to export cohort file manifest to table canceridc-user-data.user_manifests.manifest_cohort_246_20210914_214420--please contact the administrator."
![image](https://user-images.githubusercontent.com/85526819/133338307-69184b18-e171-49ef-be9e-9ef84491e808.png)

**Comment by pgundluru** [comment]
Test 2 

1. Go to https://portal.imaging.datacommons.cancer.gov/explore/
2. Select search scope - collections - TCGA CESC
3. Select related filter - Disease code - CESC, related filter - Age at diagnosis - 49, Project short code - TCGA CESC
4. Click on save cohort and then when i go to cohort page and select the cohort and click on export manifest - get BQ
Result - Successfully exported manifest!!

**Comment by pgundluru** [comment]
Test 3

Go to https://portal.imaging.datacommons.cancer.gov/explore/
Select search scope - collections - TCGA (I SELECTED ALL OF THE TCGA COLLECTIONS)
Select related filter - Disease code - CHECK ALL , related filter - Age at diagnosis - 49, Project short code - CHECK ALL
Click on save cohort and then when i go to cohort page and select the cohort and click on export manifest - get BQ
Result - Successfully exported manifest!!

**Comment by pgundluru** [comment]
Test 4

Go to https://portal.imaging.datacommons.cancer.gov/explore/
Select search scope - collections - TCGA (I SELECTED ALL OF THE TCGA COLLECTIONS)
Select original filter - Modality - CHECK ALL , original filter - body location- ALL , Species - Human 
Click on save cohort and then when I go to cohort page and select the cohort and click on export manifest - get BQ
Result - Successfully exported manifest!!

**Comment by pgundluru** [comment]
Thank you for looking at this Suzanne, I am unable to export cohort in specifically this test below for TCGA with original and related filters. 

Steps to reproduce:
System - W10 and chrome

1. In test tier https://testing-portal.canceridc.dev/explore/ 
2. Select search scope - collections - TCGA
3. Select one original filter - Body part examined - Abdomen and one related filter - Disease code - BLCA
4. Click on save cohort and then when i go to cohort page and select the cohort and click on export manifest - BQ

Result - gives following error message with nothing else in dev console "Cohort ID 241: Unable to export cohort file manifest to table idc-testing.test_user_dataset.manifest_cohort_241_20210924_170730--please contact the administrator."

![image](https://user-images.githubusercontent.com/85526819/134714173-c2e1d394-988f-4b18-b321-b2d67ce0d8f8.png)

**Comment by s-paquette** [comment]
Note: this will be handled as a hotfix.

**Comment by s-paquette** [comment]
Okay, fix for this is building on test. Since we're releasing today I'm NOT going to do this as part of the release, but as a hotfix tomorrow. @fedorov @pgundluru In about 15m (or tomorrow) if you could test this one on the test portal we can see if it's finally resolved.

**Comment by pgundluru** [comment]
Thank you for looking at this Suzanne. Unfortunately when i try the same exact test i am still unable to export to BQ

Here are my test and result:

System - W10 and chrome

In test tier https://testing-portal.canceridc.dev/explore/
Select search scope - collections - TCGA
Select one original filter - Body part examined - Abdomen and one related filter - Disease code - BLCA
Click on save cohort and then when i go to cohort page and select the cohort and click on export manifest - BQ
Result - gives following error message with nothing else in dev console 

Cohort ID 355: Unable to export cohort file manifest to table canceridc-user-data.user_manifests.manifest_cohort_355_20210928_184812--please contact the administrator.


![image](https://user-images.githubusercontent.com/85526819/135147864-a96b42c0-76e6-4328-8120-5e02b8613798.png)

**Comment by s-paquette** [comment]
@fedorov Can you confirm you can export with multiple derived filters as well? If so I think we can put this one into production.

**Comment by pgundluru** [comment]
TEST 2 

TCGA Collections with Only related filter BMI (Previously an issue) - Success

**Comment by pgundluru** [comment]
TEST 3 

TCGA Collections with only original filter (manufacture and manufacture name) - Success

**Comment by pgundluru** [comment]
TEST 4 

TCGA collections with many original filters and many related filters - success
